/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'surface-variant': '#e1e3e4',
        'tertiary-fixed': '#6ffbbe',
        'surface-container-high': '#e7e8e9',
        'primary-fixed': '#dce1ff',
        'outline-variant': '#c5c5d3',
        'surface-container-highest': '#e1e3e4',
        'surface-container-lowest': '#ffffff',
        'inverse-on-surface': '#f0f1f2',
        error: '#ba1a1a',
        'secondary-fixed': '#d8e2ff',
        'secondary-fixed-dim': '#adc6ff',
        'inverse-surface': '#2e3132',
        'error-container': '#ffdad6',
        'on-primary-fixed': '#00164e',
        'on-tertiary-fixed': '#002113',
        'surface-container-low': '#f3f4f5',
        'on-error-container': '#93000a',
        'inverse-primary': '#b6c4ff',
        'on-surface': '#191c1d',
        'surface-container': '#edeeef',
        'on-primary': '#ffffff',
        'secondary-container': '#2170e4',
        background: '#f8f9fa',
        'on-surface-variant': '#444651',
        'tertiary-container': '#004a31',
        'surface-dim': '#d9dadb',
        'on-secondary-fixed-variant': '#004395',
        tertiary: '#00311f',
        'on-background': '#191c1d',
        'on-secondary-fixed': '#001a42',
        surface: '#f8f9fa',
        'surface-tint': '#4059aa',
        'primary-fixed-dim': '#b6c4ff',
        'on-secondary-container': '#fefcff',
        'primary-container': '#1e3a8a',
        secondary: '#0058be',
        'on-primary-fixed-variant': '#264191',
        'tertiary-fixed-dim': '#4edea3',
        'on-error': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-secondary': '#ffffff',
        'on-tertiary-container': '#27c38a',
        'on-primary-container': '#90a8ff',
        'on-tertiary-fixed-variant': '#005236',
        outline: '#757682',
        'surface-bright': '#f8f9fa',
        primary: '#00236f',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'stack-sm': '8px',
        gutter: '16px',
        'stack-md': '16px',
        unit: '4px',
        'container-padding': '24px',
        'stack-lg': '32px',
      },
      fontFamily: {
        'body-lg': ['Nunito'],
        'headline-lg': ['Nunito'],
        'headline-md': ['Nunito'],
        'label-md': ['Nunito'],
        'display-lg': ['Nunito'],
        'data-mono': ['Nunito'],
        'body-md': ['Nunito'],
      },
      fontSize: {
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': ['28px', { lineHeight: '34px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'data-mono': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        // Referenced by the design's sidebar brand but missing from its config
        'headline-sm': ['16px', { lineHeight: '24px', letterSpacing: '0.01em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
