/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'surface-variant': '#e9e5ec',
        'tertiary-fixed': '#a7f3d0',
        'surface-container-high': '#e9e5ec',
        'primary-fixed': '#d7ebff',
        'outline-variant': '#e3dfe8',
        'surface-container-highest': '#e4e0e9',
        'surface-container-lowest': '#ffffff',
        'inverse-on-surface': '#f0f1f2',
        error: '#ba1a1a',
        'secondary-fixed': '#d7ebff',
        'secondary-fixed-dim': '#adc6ff',
        'inverse-surface': '#2e3132',
        'error-container': '#ffdad6',
        'on-primary-fixed': '#0b6bcb',
        'on-tertiary-fixed': '#002113',
        'surface-container-low': '#f3f0f6',
        'on-error-container': '#93000a',
        'inverse-primary': '#b6c4ff',
        'on-surface': '#1c1b1f',
        'surface-container': '#eeeaf1',
        'on-primary': '#ffffff',
        'secondary-container': '#1f66c5',
        background: '#f4f2f7',
        'on-surface-variant': '#49454f',
        'tertiary-container': '#0e7a4a',
        'surface-dim': '#e0dce4',
        'on-secondary-fixed-variant': '#004395',
        tertiary: '#0a6b40',
        'on-background': '#1c1b1f',
        'on-secondary-fixed': '#0b6bcb',
        surface: '#ffffff',
        'surface-tint': '#0b6bcb',
        'primary-fixed-dim': '#b6c4ff',
        'on-secondary-container': '#fefcff',
        'primary-container': '#0a5ab0',
        secondary: '#0b6bcb',
        'on-primary-fixed-variant': '#0a5ab0',
        'tertiary-fixed-dim': '#4edea3',
        'on-error': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-secondary': '#ffffff',
        'on-tertiary-container': '#0ee082',
        'on-primary-container': '#ffffff',
        'on-tertiary-fixed-variant': '#005236',
        outline: '#757c89',
        'surface-bright': '#ffffff',
        primary: '#0b6bcb',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '0.625rem',
        xl: '0.875rem',
        full: '9999px',
      },
      boxShadow: {
        card: '0 1px 2px rgba(16,14,23,.06), 0 1px 3px rgba(16,14,23,.05)',
        'card-lg': '0 24px 48px rgba(16,14,23,.18)',
      },
      spacing: {
        'stack-sm': '8px',
        gutter: '16px',
        'stack-md': '16px',
        unit: '4px',
        'container-padding': '24px',
        'stack-lg': '32px',
      },
      fontFamily: {
        'body-lg': ['Inter'],
        'headline-lg': ['Inter'],
        'headline-md': ['Inter'],
        'label-md': ['Inter'],
        'display-lg': ['Inter'],
        'data-mono': ['Inter'],
        'body-md': ['Inter'],
        'headline-sm': ['Inter'],
      },
      fontSize: {
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.03em', fontWeight: '600' }],
        'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'data-mono': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-sm': ['16px', { lineHeight: '24px', letterSpacing: '0.01em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};